### ISSUE TITLE
Cannot reproduce interaction clustering results

### ISSUE THREAD

**Issue by dylan-plummer** [dixonlab/scm3C-seq#7]
Hello,

I have been trying to reproduce the results from Figure 5c in the paper (https://www.nature.com/articles/s41592-019-0547-z/figures/5) using the final few lines in the clustering script and I have been unable to get any sort of positive clustering results using scHiCluster.

I followed the scHiCluster preprocessing steps as outlined in their repo: https://github.com/zhoujt1994/scHiCluster

Yet when I try running any of the scHiCluster functions (hicluster_gpu, hicluster_cpu, raw_pca) the embeddings seem practically random:

![eval](https://user-images.githubusercontent.com/13262754/88414083-4ab91780-cdaa-11ea-812c-47ec9c882b39.png)

Could you please clarify the preprocessing steps used before feeding the data into scHiCluster and would you be able to include some of the supplementary files needed to reproduce the results in the paper?

**Comment by eaststar0** [comment]
> Hello,
> 
> I have been trying to reproduce the results from Figure 5c in the paper (https://www.nature.com/articles/s41592-019-0547-z/figures/5) using the final few lines in the clustering script and I have been unable to get any sort of positive clustering results using scHiCluster.
> 
> I followed the scHiCluster preprocessing steps as outlined in their repo: https://github.com/zhoujt1994/scHiCluster
> 
> Yet when I try running any of the scHiCluster functions (hicluster_gpu, hicluster_cpu, raw_pca) the embeddings seem practically random:
> 
> ![eval](https://user-images.githubusercontent.com/13262754/88414083-4ab91780-cdaa-11ea-812c-47ec9c882b39.png)
> 
> I have spent a few days making sure that I have everything set up correctly and I believe I do, so I checked the issues in the scHiCluster repo and found that others are having similar problems running the code.
> 
> Could you please clarify the preprocessing steps used before feeding the data into scHiCluster and would you be able to include some of the supplementary files needed to actually reproduce the results in the paper?

Hi, this part (Fig. 5C) is done with "scHiCluster" and it seems you already know where to go (https://github.com/zhoujt1994/scHiCluster).
If the goal is to cluster the single-cell hi-c data, I can help you out (Fig. 4e).
If the goal is to run scHiCluster, you have to contact Jingtial Zhou, one of the authors on the paper.

Thanks

Dongsung

**Comment by dylan-plummer** [comment]
Hi, thank you for the reply! I am specifically interested in running scHiCluster on the data as demonstrated in the final lines of the `clustering.py` script:

```python
hg19dim = [249250621,243199373,198022430,191154276,180915260,171115067,159138663,146364022,141213431,135534747,135006516,133851895,115169878,107349540,102531392,90354753,81195210,78077248,59128983,63025520,48129895,51304566,155270560]
network = np.loadtxt(outdir + 'cell_matrix/sample_list_hic.txt', dtype=np.str)
chrom = [str(i+1) for i in range(22)]
chromsize = {chrom[i]:hg19dim[i] for i in range(len(chrom))}
nc = 10
cluster, matrix_reduce = hicluster_gpu(network, chromsize, nc=nc)
```

I will try to contact Jingtial Zhou for help.

**Comment by dylan-plummer** [comment]
I was able to reproduce the results using the independent implementation included within the scHiCTools package: https://github.com/liu-bioinfo-lab/scHiCTools

![image](https://user-images.githubusercontent.com/13262754/89219154-486e6e80-d59d-11ea-90ca-a07a1a86a77e.png)
